[package]
name = "atomic-data-publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "chrono", "uuid", "bigdecimal"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
config = "0.13"
dotenv = "0.15"
thiserror = "1.0"
futures = "0.3"
helium-proto = { git = "https://github.com/helium/proto", branch = "master", features = [ "services"] }
helium-crypto = { git = "https://github.com/helium/helium-crypto-rs.git", branch = "main" }
tonic = { version = "0.14", features = ["tls-aws-lc", "tls-native-roots"] }
prost = "0.14"
bs58 = "0.5"
base64 = "0.22"
rand = "0.8"
metrics = "0.23"
metrics-exporter-prometheus = "0.15"
triggered = "0.1"
reqwest = "0.12.14"
aws-config = "1.8"
aws-credential-types = "1.2.4"
aws-sdk-rds = "1.112.1"
sha2 = "0.10.9"
hmac = "0.12.1"
hex = "0.4"
urlencoding = "2.1"

#[patch.'https://github.com/helium/proto']
#helium-proto = { git = "https://www.github.com/helium/proto", branch = "mj/chain-rewardable-entities" }
