[package]
name = "standardize-hotspot-metadata"
version = "0.0.1"
edition = "2021"

[profile.release]
overflow-checks = true

[dependencies]
solana-client = "1.17.22"
serde_json = "1.0"
reqwest = { version = "0.11.13", features = ["blocking", "json"]  }
serde = "1.0.152"
solana-sdk = "1.17.22"
bincode = "1.3.3"
warp = "0.3.3"
futures = "0.3.25"
lazy_static = "1.4.0"
anchor-lang = "0.28.0"
clap = { version = "4.3.9", features = ["derive"] }
tokio = "1.29.0"
anchor-client = { version = "0.28.0", features = ["async"] }
anyhow = "1.0.71"
chrono = "0.4.26"
helium-entity-manager = { path = "../../programs/helium-entity-manager" }
hpl-utils = { path = "../hpl-utils" }
bs58 = "0.4.0"
sha2 = "0"
