[package]
name = "bulk-claim-rewards"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0"
anyhow = "1"
anchor-lang = "*"
anchor-spl = "0"
anchor-client = "*"
byteorder = "1.3.2"
hmac = "0"
sha2 = "0"
clap = { version = "4", features = ["derive"]}
helium-crypto = { version = "0.7.3", features = ["solana"] }
reqwest = "0"
helium-entity-manager = { path = "../../programs/helium-entity-manager", features = [ "no-entrypoint" ] }
circuit-breaker = { path = "../../programs/circuit-breaker", features = [ "no-entrypoint" ] }
lazy-distributor = { path = "../../programs/lazy-distributor", features = [ "no-entrypoint" ] }
rewards-oracle = { path = "../../programs/rewards-oracle", features = [ "no-entrypoint" ] }
helium-sub-daos = { path = "../../programs/helium-sub-daos", features = [ "no-entrypoint" ] }
hpl-utils = { path = "../hpl-utils" }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
json = "*"
lazy_static = "1"
rand = "0.8"
sodiumoxide = "~0.2"
solana-account-decoder = "*"
solana-client = "*"
solana-sdk = "*"
solana-program = "*"
spl-associated-token-account = { version = "*", git = "https://github.com/ChewingGlass/solana-program-library", features = [ "no-entrypoint" ] }
thiserror = "1"
helium-api = "3"
rust_decimal = "1"
bincode = "1.3.3"
hex = "0.4.3"
bs58 = "0.4.0"
tokio = "1.14.1"
futures = "0.3.28"
