[package]
name = "ecc-sig-verifier"
version = "0.0.14"
edition = "2021"

[profile.release]
overflow-checks = true

[dependencies]
solana-sdk = "1.16.13"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
helium-crypto = "0.7.3"
hex = "0.4.3"
serde = "1.0.157"
bincode = "1.3.3"
anchor-lang = "*"
reqwest = { version = "0.11.13", features = ["json"]  }
time = "0.3.36"
